version: '3'

services:
  docker_dev:
    image: ubuntu:focal
    container_name: docker_dev
    environment:
      - TZ=America/Denver
    volumes:
      - /entrypoint.sh:/entrypoint.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    tty: true
    stdin_open: true
    command: ["/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '12.0'
          memory: 4096M
    restart: unless-stopped
